### ISSUE TITLE
Report portal launch Link

### ISSUE THREAD

**Issue by amartanwar42** [BorisOsipov/wdio-reportportal-reporter#120]
Is this possible to get the report portal launch link in afterSuite()

Problem Statement:
I am getting the report portal link incomplete(). But at this step, I can only print in console.

If I can get report portal launch link in afterSuite() I can use it send to slack

**Comment by BorisOsipov** [comment]
@amartanwar42 have you tried just move `const link = await RpService.getLaunchUrl(config);` from `onComplete` to `afterSuite`? It should work. Any errors?

**Comment by amartanwar42** [comment]
My code: 
  afterSuite: async function (_, config) {
    const link = await RpService.getLaunchUrl(config);
    launchURL = link;
    console.log(`Report portal link suite ${launchURL}`);
  },

and error which I am getting:
 ERROR @wdio/sync: TypeError: Cannot read property 'reporters' of undefined
    at Function.getRpReporterConfig (/Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/wdio-reportportal-service/src/index.js:51:30)
    at Function.getLaunchUrl (/Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/wdio-reportportal-service/src/index.js:70:32)
    at Object.afterSuite (/Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/wdio.conf.js:74:34)
    at execHook (/Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/@wdio/sync/build/executeHooksWithArgs.js:32:23)
    at /Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/@wdio/sync/build/executeHooksWithArgs.js:48:56
    at new Promise (<anonymous>)
    at /Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/@wdio/sync/build/executeHooksWithArgs.js:25:29
    at Array.map (<anonymous>)
    at executeHooksWithArgs (/Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/@wdio/sync/build/executeHooksWithArgs.js:25:17)
    at Context.<anonymous> (/Users/durgaverma/Documents/HelloBetter/Projects/patientapp-web-automation/node_modules/@wdio/mocha-framework/build/index.js:148:50)

**Comment by BorisOsipov** [comment]
@amartanwar42 `const link = await RpService.getLaunchUrl(this);` will help.
