### ISSUE TITLE
WDIO v6 throws error:Error: Some reporters are still unsynced: ReportPortalReporter

### ISSUE THREAD

**Issue by yanivyu1** [BorisOsipov/wdio-reportportal-reporter#136]
## The problem
running specs without a tag cause this error to appear and open a new undefined run in the reportportal dashboard
Briefly describe the issue you are experiencing or the feature you want) Tell us what you were trying to do and what happened instead.

## Environment

* WebdriverIO version:6
* wdio-reportportal-version version:6.1.2
* Node.js version:12
* WDIO Testrunner and version(mocha\cucumber\jasmine):mocha 6.11.2
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
>running specs without a tag cause this error to appear 

what do you mean? can you share reproduceable example and screenshots?

**Comment by yanivyu1** [comment]
i'm running the framework vs GridLastic with ReportPortal and all the filtered specs shows the error i sent you
here is the reportportal config in the wdio.conf.js 
![image](https://user-images.githubusercontent.com/21429177/104598157-ea32d500-567e-11eb-8186-af12d46d77db.png)

**Comment by yanivyu1** [comment]
?

**Comment by BorisOsipov** [comment]
Reproduceable example still missing. How can I fix\investigate issue if I don't know how to reproduce it?

I need sample project I can run and investigate issue. Or at least setup "debug: true" in reporter config and share with me full test run job by email(in profile).

**Comment by BorisOsipov** [comment]
Also show reporter and service section from wdio config.

**Comment by yanivyu1** [comment]
Start launch 2shpscr9kjyhryoc
Error: Request failed with status code 403: {"errorCode":4003,"message":"You do not have enough permissions."}
    at /Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/reportportal-js-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-15T16:24:14.869Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Request failed with status code 403: {"errorCode":4003,"message":"You do not have enough permissions."}
    at /Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/reportportal-js-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by yanivyu1** [comment]
the reason for the no permission was due i set the wrong project in report portal, this is the log when configuring the correct project
gs://apps.gs-secrets.staging.zoominfo.com/qa-automation-app-users.json.enc download start.
Start launch 2shpsillkjypvknq
[0-0] 2021-01-15T20:11:11.303Z ERROR @wdio/runner: Error: Some reporters are still unsynced: ReportPortalReporter
    at Timeout.<anonymous> (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/@wdio/runner/build/reporter.js:69:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Finish launch 2shpsillkjypvtkz
Success finish launch 2shpsillkjypvtkz

**Comment by BorisOsipov** [comment]
@yanivyu1 no ideas why. I checked, reporter works fine with latest wdio\report portal versions.
Please double check your configuration\setup\etc. 
Sorry, I can spend time guessing what is wrong with your setup without full config\logs and seems you don't want do it.

**Comment by yanivyu1** [comment]
how can i share my code and not here?

**Comment by BorisOsipov** [comment]
Create [Short, Self Contained, Correct example](http://sscce.org/) repo and share with me by link or invite if you don't want share it in public.

**Comment by yanivyu1** [comment]
since it is not my private repo, can you be more specific on what code/config you require and i'll share that and not the all project

**Comment by BorisOsipov** [comment]
Please, take my public repo, make fork, modify config\specs\etc to reproduce your issue. Then commit-push and share with me.
https://github.com/BorisOsipov/wdio-rp-testrepo

If you need share something not public - my contacts in github profile.

**Comment by yanivyu1** [comment]
i tried to commit with no success, github issue in my part. the major change i did is to add grep:"yanivyu1" to the mochaOpts and add a onPrepare method with console.log('On prepare'); inside. i tired to run with the changes i made and the same errors appears

**Comment by BorisOsipov** [comment]
@yanivyu1 thank you. I partially reproduce your issue. 
I removed excess specs and add "yanivyu1" to few spec names.
If there are some `mochaOpts` for all specs are not matched `yanivyu1`reporter spams `Some reporters are still unsynced: ReportPortalReporter`. But it is not terrible - it is not break anything in reporting - I see in report portal UI finished launch with all completed tests. It is just weird spam in log. I will see how to fix spam logs.

>running specs without a tag cause this error to appear and open a new undefined run in the reportportal dashboard

but I don't see `a new undefined run ` in report portal. how can I reproduce it?

**Comment by BorisOsipov** [comment]
Spam `Some reporters are still unsynced:` for not matched specs fixed in 6.1.3

**Comment by yanivyu1** [comment]
Thank you!!!

**Comment by BorisOsipov** [comment]
@yanivyu1 you're welcome. Please, check that fix helps in your project.

**Comment by yanivyu1** [comment]
the error message dissappeared
