### ISSUE TITLE
Reporter crashes if suite failed by before hooks

### ISSUE THREAD

**Issue by BorisOsipov** [BorisOsipov/wdio-reportportal-reporter#16]
## The problem

Reporter crashes if suite failed by before hooks

## Environment

* WebdriverIO version: v4
* wdio-reportportal-version version: 0.0.10
* WDIO Testrunner and version(mocha\cucumber\jasmine): cucumber

## Details

```
C:\work\tests\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
TypeError: Cannot read property 'id' of null
    at ReportPortalReporter.suiteEnd (C:\work\tests\node_modules\wdio-reportportal-reporter\build\reporter.js:112:59)
    at ReportPortalReporter.emit (events.js:182:13)
    at ReportPortalReporter.EventEmitter.emit (domain.js:442:20)
    at BaseReporter.handleEvent (C:\work\tests\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
    at Launcher.messageHandler (C:\work\tests\node_modules\webdriverio\build\lib\launcher.js:688:28)
```

**Comment by BorisOsipov** [comment]
Still actual. Need investigate and fix
