### ISSUE TITLE
ReferenceError: issue_type is not defined in v0.0.16

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#26]
## The problem

 ReferenceError: issue_type is not defined in version 0.0.16 when running any test

## Environment

* WebdriverIO version: 4.11
* wdio-reportportal-version version: 0.0.16
* Node.js version: 8.10
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha
* Additional wdio packages used (if applicable):

## Details
with new version of wdio-report-portal test fails on launch:
```
Failed loading configuration file: /Users/208821/Projects/np-cooking/api/test/e2e/wdio.conf.local2.js
/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/build/lib/utils/ConfigParser.js:194
                throw e;
                ^

ReferenceError: issue_type is not defined
    at Object.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/wdio-reportportal-reporter/build/reporter.js:326:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/pages/page.js:1:80)
```

Looks like in build/reporter.js extra constructor appearing. But lib/reporter.js looks identical in v0.0.15 and in v0.0.16:

build/reporter.js:
```
class Issue {
    // tslint:disable-next-line
    constructor(issue_type) {
        this.issue_type = issue_type;
    }
}
// tslint:disable-next-line
`line 326`: constructor(issue_type);  //reference error here
{
    this.issue_type = issue_type;
}
```

Removing second constructor solves reference error

**Comment by BorisOsipov** [comment]
@igerasimov23 rebuilded and published as 0.0.17. Thanks!
