### ISSUE TITLE
Does not  displays any logs unless test FAILED

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#5]
Looks like wdio-reportportal-reporter does not send any logs to reportPortal during execution but I have ` logLevel: 'data'`. It send only failure logs if test failed

<img width="1332" alt="screen shot 2018-09-26 at 10 57 45 am" src="https://user-images.githubusercontent.com/15241367/46088744-0abb8600-c17b-11e8-906a-f795a4983752.png">

**Comment by igerasimov23** [comment]
Do we have any dates for that feature? Ss we still did not decided to use JS client to post result to reportportal or wdio-reportportal-reporter

**Comment by igerasimov23** [comment]
you right with `logLevel:data` it's just pretty format of selenium logs
``` [20:07:24]  DATA		{"using":"css selector","value":"div.nytc---newcollectionbutton---container span"}
[20:07:24]  DATA		{"using":"css selector","value":"div.nytc---newcollectionbutton---container span"}
[20:07:24]  DATA		{}
[20:07:25]  DATA		{"using":"css selector","value":"[data-id='recently-viewed'] .nytc---listitem---name"}
[20:07:25]  DATA		{"using":"css selector","value":"[data-id='recently-viewed'] .nytc---listitem---name"}
[20:07:25]  DATA		{"using":"css selector","value":"[data-id='recently-viewed'] .nytc---listitem---name"}
[20:07:25]  DATA		{}
[20:07:25]  DATA		{}
[20:07:26]  DATA		{"using":"css selector","value":"a.nytc---breadcrumbs---[*******]Guides"}
[20:07:26]  DATA		{}
[20:07:26]  DATA		{"using":"css selector","value":".nytc---draganddrop---dragWrapper:nth-of-type(1) .nytc---cardbase---card"}
[20:07:27]  DATA		{"using":"css selector","value":".nytc---draganddrop---dragWrapper:nth-of-type(1) .nytc---cardbase---card"}
[20:07:27]  DATA		{}
[20:07:27]  DATA		{"using":"css selector","value":".nytc---cardbase---imageWrap img"}
[20:07:27]  DATA		{"using":"css selector","value":".nytc---cardbase---imageWrap img"}
[20:07:27]  DATA		{"using":"css selector","value":".nytc---cardbase---cardRecipeInfo"}
[20:07:27]  DATA		{"using":"css selector","value":".nytc---cardbase---cardRecipeInfo"}
[20:07:27]  DATA		{}
[20:07:28]  DATA		{"using":"css selector","value":"h3.nytc---cardbase---name"}
[20:07:28]  DATA		{"using":"css selector","value":"h3.nytc---cardbase---name"}
[20:07:28]  DATA		{}
[20:07:28]  DATA		{"using":"css selector","value":"p.nytc---cardbase---cardByline"}
[20:07:28]  DATA		{"using":"css selector","value":"p.nytc---cardbase---cardByline"}
[20:07:28]  DATA		{}
[20:07:28]  DATA		{"using":"css selector","value":".nytc---cardcontrols---cardIndicators"}
[20:07:28]  DATA		{"using":"css selector","value":".nytc---cardcontrols---cardIndicators"} ```

I think selenium logs will ok as well to send. Can we do it through feature flag(we did for slackreporter the same way):
``` reporterOptions: {
            sendSelLogs: true or false
} ```
We can do screenshots on failure also using feature flag.

I looked today over code and I saw it should it support screenShot on failure. But it have never worked for me. If you post in readme how to do it will be awesome.

But I more want to know how you can add custom logs using API you created(docs will be helpful). If  we will decide to go with your reporter we can contribute as well to this project.

I saw that you under Epam so I thought you doing as project for them.

**Comment by igerasimov23** [comment]
Hi,

Unfortunately was not able to run test at all, due following error:
``` 
/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/reportportal-client/lib/report-portal-client.js:21
        this.debug = params.debug;
                            ^

TypeError: Cannot read property 'debug' of undefined
    at new RPClient (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/reportportal-client/lib/report-portal-client.js:21:29)
    at new ReportPortalReporter (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/wdio-reportportal-reporter/build/reporter.js:40:19)
    at Launcher.initReporters (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/build/lib/launcher.js:209:30)
    at new Launcher (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at launch (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/build/lib/cli.js:452:24)
    at Object.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/build/lib/cli.js:485:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/bin/wdio:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
``` 

My config: 
``` 
reporters: ['spec', 'dot', 'reportportal'],
  reporterOptions: {
    reportportal: {
      token: 'bf024753-a9f2-4821-8ad0-6ab698055b3c',
      endpoint: 'http://35.185.61.123/api/v1',
      launch: 'launch_name',
      project: 'cooking',
      mode: 'DEFAULT'
    },
    enableSeleniumCommandReporting: true,
    enableScreenshotsReporting: true,
    seleniumCommandsLogLevel: 'debug',
    screenshotsLogLevel: 'info',
  },
```

Also from readme file in your Moca example you have:
`const reporter = require('wdio-allure-reporter');` I think it should be `const reporter = require('wdio-reportportal-reporter')`

**Comment by BorisOsipov** [comment]
@igerasimov23 thanks for help with this.

I wrote in previos message "Pay attention I changed the reporter config - now all RP related options on rpConfig object."
So your wdio.conf.js should be 
```
reporters: ['spec', 'dot', 'reportportal'],
  reporterOptions: {
    reportportal: {
		rpConfig :{
			  token: 'bf024753-a9f2-4821-8ad0-6ab698055b3c',
		      endpoint: 'http://35.185.61.123/api/v1',
		      launch: 'launch_name',
		      project: 'cooking',
		      mode: 'DEFAULT'
		},
	    enableSeleniumCommandReporting: true,
	    enableScreenshotsReporting: true,
	    seleniumCommandsLogLevel: 'debug',
	    screenshotsLogLevel: 'info',    
    }
  },
```
I think it is good to separate RP configs with reporter config. What do you think?

>Also from readme file in your Moca example you have:

yes I've fixed it in [commit](https://github.com/BorisOsipov/wdio-reportportal-reporter/commit/f7bdc73f54c6d98e1a26e98a6e5629c4bce0652f)

**Comment by BorisOsipov** [comment]
@igerasimov23 Also are please invalide `token: 'bf024753-a9f2-4821-8ad0-6ab698055b3c',` or I may remove\edit your commentы. I am worried about security issues.

**Comment by BorisOsipov** [comment]
I've replaced your token with `xxxxx` to be sure it's invalid.

**Comment by BorisOsipov** [comment]
>But overall I REALLY LIKE logger implementation. Did you do base on Allure implementation?

yes, I am wdio-allure-reporter maintener and adopt some functions from them.

**Comment by igerasimov23** [comment]
After some hours of testing, found following issues with new implementation:
1. if in test we have retry option `this.retries(2)` and if test fails - test status will be in progress and test will never finish
2. if feature `enableScreenshotsReporting: false` set and in afterTest hook 
``` if (test.passed === false) {
      const screenshot =   browser.saveScreenshot();
      reporter.sendFileToLastFailedTest('info', 'failed.png', screenshot);
    }
```
if will post screenshots anyway into RP
3. is this mothod `sendFileToLastFailedTest` implemented as async function? I tried set the same way as you did in readme:
``` 
afterTest: async function afterTest(test) {
    if (test.passed === false) {
      const screenshot = await browser.saveScreenshot();
      reporter.sendFileToLastFailedTest('error', 'failed.png', screenshot);
    }
  },
``` 
but it still could not post screenshots and test status was in progress.
I was trying cover with Promise but still could not do it successfully. I did this way:
``` afterTest: function (test) {
    if (test.passed === false) {
      const screenshot =   browser.saveScreenshot();
      browser.pause(5000)
      reporter.sendFileToLastFailedTest('info', 'failed.png', screenshot);
      browser.pause(10000)
    }
  },
 ``` it works but really don't like this approach with static waits. Any thoughts?

**Comment by BorisOsipov** [comment]
1) yes it is an issue https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/2
2) yes, why not? if you send file why should we forbid it by some unrelated option? 
3) `sendFileToLastFailedTest` is synchronous. It only sends an event to reporter with file data.
>but ... test status was in progress.

yes it is the same retries issue, isn't it?

>it works but really don't like this approach with static waits. Any thoughts?
No, rigth now. I guess some data race. Will see how deal with it.

**Comment by igerasimov23** [comment]
Question regarding functionality `enableScreenshotsReporting: false`, what is the purpose of it if it post screenshots anyway when is true or false?

**Comment by igerasimov23** [comment]
For retries, when I pass retry= true, ` const testStartObj = { type: entityType.TEST, name: test.title, retry: true };` looks like the same test creates as child of the same test(so test session never gets finished):
<img width="1248" alt="screen shot 2018-09-29 at 9 49 55 pm" src="https://user-images.githubusercontent.com/15241367/46252104-37e58e00-c432-11e8-8e34-feeae4eda0d3.png">

**Comment by BorisOsipov** [comment]
[Moved third issue](https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/5#issuecomment-425564732) to separrate issue https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/7
