### ISSUE TITLE
ReportPortal not finishing launch for WDIOv5

### ISSUE THREAD

**Issue by dragancla** [BorisOsipov/wdio-reportportal-reporter#70]
After running a suite in a certain number of parallels (we tried 15 and 10) @wdio/local-runner fails because ReportPortalReporter is unsynced at the end of the test so the launch never finishes.

I get this after certain tests fail:
```
[3-54] 2019-07-17T12:13:01.888Z ERROR @wdio/local-runner: Failed launching test session: Error: Some reporters are still unsynced: ReportPortalReporter
    at Timeout.setInterval (/usr/src/app/node_modules/@wdio/runner/build/reporter.js:121:25)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
[3-54] FAILED in chrome - /test/54/path

[6-53] 2019-07-17T12:13:11.655Z ERROR @wdio/local-runner: Failed launching test session: Error: Some reporters are still unsynced: ReportPortalReporter
    at Timeout.setInterval (/usr/src/app/node_modules/@wdio/runner/build/reporter.js:121:25)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
[6-53] FAILED in chrome - /test/53/path

[3-55] 2019-07-17T12:13:15.950Z ERROR @wdio/local-runner: Failed launching test session: Error: Some reporters are still unsynced: ReportPortalReporter
    at Timeout.setInterval (/usr/src/app/node_modules/@wdio/runner/build/reporter.js:121:25)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
[3-55] FAILED in chrome - /test/55/path
``` 

And I get this at the end of the stack trace:
```
Error: Request failed with status code 406: {"error_code":40023,"message":"Finish launch is not allowed. Launch '5d2f0a1fd1759f0001ce5540' has items '[5d2f10aad1759f0001ce6db6]' with 'IN_PROGRESS' status"}
    at axios.then.catch (/usr/src/app/node_modules/reportportal-js-client/lib/rest.js:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: Request failed with status code 406: {"error_code":40023,"message":"Finish launch is not allowed. Launch '5d2f0a1fd1759f0001ce5540' has items '[5d2f10aad1759f0001ce6db6]' with 'IN_PROGRESS' status"}
    at axios.then.catch (/usr/src/app/node_modules/reportportal-js-client/lib/rest.js:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I would share reproducible test code but if we run those tests separately they do work and report failures and finish the launches. It happens for 3 tests in quick succession (15 seconds total), the other 1500 tests work OK, so I guess we're overloading the RP queue?

**Comment by BorisOsipov** [comment]
Hi @dragancla 

I've met this issue few times, but don't know what the root cause is. Also I heard that some non-wdio users with other integrations implementations ran into this - so maybe it is report portal perfomance issue. Can't fix\suggest something without a reproducable example.

**Comment by iamkenos** [comment]
Hi! Is there a way to supress this error into a warning instead?

**Comment by BorisOsipov** [comment]
@iamkenos yes. good idea. will add

**Comment by BorisOsipov** [comment]
@dragancla @iamkenos 

First, If you ran into `[6-53] 2019-07-17T12:13:11.655Z ERROR @wdio/local-runner: Failed launching test session: Error: Some reporters are still unsynced: ReportPortalReporter
 `
you may increase sync timeout to allow reporter send all data and avoid corrupted launches. It can be done by wdio config
```
exports.config = {
 ...
	reporterSyncInterval: 10 * 1000 // in ms. default 5000
 ...  
}
```

Second. I suppress `Error: Request failed with status code 406: {"error_code":40023,"message":"Finish launch is not allowed. Launch '5d2f0a1fd1759f0001ce5540' has items '[5d2f10aad1759f0001ce6db6]' with 'IN_PROGRESS' status"}
` error in reporter. Now you will see only warning on this error.
I made PR to wdio to only log error
`[6-53] 2019-07-17T12:13:11.655Z ERROR @wdio/local-runner: Failed launching test session: Error: Some reporters are still unsynced: ReportPortalReporter
 ` but not fail wdio test run.

So now(after next wdio-runner release v5.15.2+) you won't get this error, but still have some inconsistent launches on errors from rp side.

**Comment by anandbhagwat** [comment]
Hi @BorisOsipov How do you suppress this in warning? could you please? I am also facing this issues.
I also added reporterSyncInterval: 10 * 1000

**Comment by BorisOsipov** [comment]
@anandbhagwat 
>How do you suppress this in warning?

there is no way.
