### ISSUE TITLE
ReportPortalReporter unsynced and does not finish session

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#94]
## The problem

ReportPortalReporter becomes unsynched on slow internet connection

## Environment

* WebdriverIO version: 5.15.1
* wdio-reportportal-version version: 5.2.2
* Node.js version: 10.16.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha
* Additional wdio packages used (if applicable):

## Details

Ran a build when internet connection was slow and getting unsynched error
```
[0-0] 2019-11-11T18:02:31.244Z ERROR @wdio/runner: Error: Some reporters are still unsynced: ReportPortalReporter
    at Timeout.setInterval (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/@wdio/runner/build/reporter.js:86:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[0-0] FAILED in chrome - /test/users/regi/test-post-free-trial-permissions.js
Error: Request failed with status code 406: {"error_code":40023,"message":"Finish launch is not allowed. Launch '5dc9a1b16fdf1c0001c7fe8b' has items '[5dc9a20f6fdf1c0001c7fe8d,5dc9a2106fdf1c0001c7fe8e]' with 'IN_PROGRESS' status"}
    at axios.then.catch (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/reportportal-js-client/lib/rest.js:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Can't finish Report portal launch due errors
Request failed with status code 406: {"error_code":40023,"message":"Finish launch is not allowed. Launch '5dc9a1b16fdf1c0001c7fe8b' has items '[5dc9a20f6fdf1c0001c7fe8d,5dc9a2106fdf1c0001c7fe8e]' with 'IN_PROGRESS' status"}
```

## Code To Reproduce Issue [ Good To Have ]
```
describe('test', function () {
  this.retries(3);
  it('test', () => {
    browser.url('https://www.google.com');
    assert.isTrue(false)
  });
}); 
```
```
afterTest: function (test, context, { error, result, duration, passed, retries }) {
    if (test.passed) {
      const passMsg = `******* TEST '${test.title}' PASSED ******* `;
      console.info(passMsg);
      reporter.sendLogToTest(test, 'info', passMsg);
    } else {
      const failMsg = `******* TEST '${test.title}' FAILED ******* `;
      console.info(failMsg);
      reporter.sendLogToTest(test, 'info', failMsg);
      if (reportPortalUUID) {
        const screenshot = browser.saveScreenshot(`./screenshots/${test.title}.png`);
        reporter.sendFileToTest(test, 'info', `${test.title}.png`, screenshot);

      }
    }
}
```

**Comment by BorisOsipov** [comment]
Just to check, maybe you missed https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/70#issuecomment-544237750

**Comment by BorisOsipov** [comment]
Also the error `{"error_code":40023,"message":"Finish launch is not allowed. Launch '5dc9a1b16fdf1c0001c7fe8b' has items '[5dc9a20f6fdf1c0001c7fe8d,5dc9a2106fdf1c0001c7fe8e]' with 'IN_PROGRESS' status"}`
sometimes appears. I don't have reliable example to reproduce it.

I can't do any thing with it. Report Portal guys make promise it will not occur in Report Portal v5. I send all data to make launch\suites\test case completed, but it still occurs for v4 sometimes. I also know that some guys from java reportes suffer with the same problems

**Comment by igerasimov23** [comment]
I think I missed #70 (comment) which solves problem on slow internet connection
